### ISSUE TITLE
removeAdditional optionally during validation, rather than creation of Ajv object

### ISSUE THREAD

**Issue by mbroadst** [epoberezkin/ajv#200]
Currently `removeAdditional` must be specified when creating the `Ajv` object, and the behavior is maintained for all subsequently compiled validators. It seems more reasonable to me that we be able to pass this as an option to a validator itself, e.g.
```
let ajv = new Ajv();
let validate = ajv.compile(schema);
let valid = validate(someData, { removeAdditional: true });
...
```

Would there be any objection to supporting this? Can you think of possible pitfalls to this solution?

In my particular case, the existing validation engine supports this type of behavior - so that's my use case. I would prefer not to have to create a new ajv object just to remove additionals.

**Comment by epoberezkin** [comment]
Need to think about it...
Problems:
1. Validation function receives 4 arguments, not just data.
2. It would affect performance for the main use case

I was also thinking about schema level options (rather than validation-time options) but it also adds a lot of complications...

**Comment by epoberezkin** [comment]
Was thinking... Probably performance overhead of creating an additional instance is less that checking such options at validation time.

The solution could be to have some compilation time option(s) that would whitelist option(s) that should be supported at validation time (to avoid performance cost in general case, and to generate code that would support such options).

It still requires changing validation function signature to pass these options, so should be a major version change. Alternatively it could be some method to set validation time options that would apply to all subsequent calls... Not sure I like such api though.

The reason you can't have schema level options easily, by the way, is because schemas may have dependencies and they should be compiled with the same options; so caching compiled schemas becomes difficult - options they were compiled with should be taken into account.

The more I think about all this complexities, having multiple instances seems to be the right way. What are your arguments against it, apart from some aesthetics? This complexity should live somewhere and having it in your app rather than inside ajv has both performance benefits and also reduces total complexity...

**Comment by mbroadst** [comment]
frankly my desire for the feature was just to maintain parity with the schema system I was replacing. They supported options on all levels, but I've never needed such behavior in my production code and considering I'm the only user of the new codebase so far I'm content to leave the feature out.

This was more of a question to discuss whether it was possible, and if so what the implications would be and I think that desire has been satisfied. I'll close the issue now pending future discussion where someone brings up a valid use case.

**Comment by slavafomin** [comment]
Too bad this wasn't considered in the newer version of the library. Having `removeAdditional` option on a per-schema (or even per-call) level seems very logical and convenient. Actually, I've spent half an hour trying to figure out how to pass this option to the compilation/validation function. ChatGPT made me believe that it was possible 😂

Creating two different instances of the ajv just to alter the behavior of a validation function seems like a DX nightmare.

@epoberezkin please reconsider 😄
